### ISSUE TITLE
TypeScript is used as a dependency instead of a devDependency

### ISSUE THREAD

**Issue by opl-** [TheRealSyler/suf-cli#2]
TypeScript, when used only to build the package, should be specified as a `devDependency`. The package should be built before being published to npm, which makes TypeScript unnecessary when installing this package as a dependency for projects that are written in pure JavaScript.

This is supported by the TypeScript download page suggesting the use of `--save-dev`: https://www.typescriptlang.org/id/download

**Comment by TheRealSyler** [comment]
fixed with 8a1c33d
